### ISSUE TITLE
Research failure modes for bosh-related jobs

### ISSUE THREAD

**Issue by jamieklassen** [concourse/ci#12]
## Observation
Lots of failures in bosh-related testing jobs, and most of them seem to concern failed deploys. Honestly I don't understand them very well, and I'm a bit worried that countermeasures like concourse/concourse#3945 won't help.

## Hypothesis
I don't have a lot of confidence here, and am happy for folks to weigh in. @vito's suggestion was that the bosh director is getting overwhelmed by parallel tasks. The supporting argument is that we have more deployments than ever before, since we are running deploys for multiple release and feature branches as well as wings.

## Experiment
This is admittedly a heavyweight suggestion (as pointed out by @cirocosta), but it involves the least working knowledge of bosh: we could modify our pipeline to distribute the deploys across multiple directors, and compare
* frequency of deploy failures
* frequency of test flakes

over time. This approach does carry a lot of unknowns, (though @taylorsilva's suggestion to use toolsmiths could offload some of those), so hopefully there's a less-costly experiment that we can run? Slightly lighter-weight is the below suggestion to scale the bosh director vertically. Can we do even better than that? Maybe we can run some query directly against the bosh director in its current state, or maybe just investigate the failure logs we already see, or else set up some kind of proactive monitoring and wait a while?

**Comment by taylorsilva** [comment]
Toolsmiths comes to mind right away for me as a way to ensure we get **clean** bosh environments and can spread the load out among many directors. Plus we wouldn't have to manage any of these directors.

Toolsmiths has a pool of directors that you can grab from whenever you want to. So we could ask things like:

> hey toolsmiths, give me 5 bosh directors please

and they'll just give you 5 right away, assuming the pool isn't dry, which it usually isn't.

**Comment by cirocosta** [comment]
Hey @pivotal-jamie-klassen,

>  and most of them seem to concern failed deploys.

When we say that there are "deployment errors", what does that mean under the hood? Is it BOSH failing to acquire a lock? 

> **Hypothesis** - The bosh director is getting overwhelmed by parallel tasks

Is there a simpler way that we could verify this without going full on having multiple directors (seems like a more complex way of verifying)? I wonder if it'd be a matter of vertically scaling the director and increasing the number of parallel workers 🤔

**Comment by xtreme-sameer-vohra** [comment]
second @cirocosta 
It would be useful to understand the nature of the failed deploys prior to weighing in on possible solutions. 

Depending on the problem the director can be scaled vertically, including increasing the [number of worker processes on the director](https://github.com/cloudfoundry/bosh/blob/master/jobs/director/spec#L73-L75)

**Comment by pivotal-jamie-klassen** [comment]
@taylorsilva @cirocosta @xtreme-sameer-vohra while you're here, maybe I can ask: how would *you* get a better sense of what's going on the bosh director?
* Would you check the VM metrics on GCP?
* login via SSH to the director yourself, looking for logs somewhere?
* does bosh itself have any tools to help with this?

While I'm happy to learn, this is an area where I don't have much knowledge, and if somebody else can swoop in and get the pipeline unclogged faster than me that would be rad.

**Comment by xtreme-james-thomson** [comment]
So I just took a look at the past 30000 bosh tasks, with the command `bosh -e prod tasks --recent=30000 --all` and grepped for `error` and I can see main issues that are causing errors.

1. get_task failed
example: `Action Failed get_task: Task f4b543a9-ee1c-48f1-724a-5951ed432421 result: Stopping Monitored Services: Stopping services...`
2. Timed out pinging a vm
example `Timed out pinging to 20fc959d-f865-4e7e-90b6-bfc2a3914fcd after 600 seconds`
3. VM creation failed 
example `CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: Google Operation...`

______

Slight investigation:
1. Looking into a task with that get_task error, by going `bosh -e prod task 1400866 --debug` it shows a bit more:
```
D, [2019-06-07T14:29:52.723206 #13494] [] DEBUG -- DirectorJobRunner: RECEIVED: director.965c37f3-3f0d-4814-a675-2eea08e43479.95aad46f-dede-4f06-a3a6-b20d4754decb.bdae88c2-b6db-463a-8756-764b7f0d50a4 {"exception":{"message":"Action Failed get_task: Task 497b0567-969d-46fb-5f75-9b2b89e14fb1 result: Stopping Monitored Services: Stopping services '[worker]' errored"}}
```
and
```
E, [2019-06-07T14:29:52.730578 #13494] [canary_update(worker/349641d6-6d41-48ab-b8b3-409c88194098 (14))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::RpcRemoteException: Action Failed get_task: Task 497b0567-969d-46fb-5f75-9b2b89e14fb1 result: Stopping Monitored Services: Stopping services '[worker]' errored>
```

_______

2. Looking into this one, it just looks like the vm either didn't spin up in time (10 min), or there was some issue with that vm spinning up that it couldn't be contacted within the 10 min.
```
E, [2019-06-06T20:36:13.168002 #19796] [create_missing_vm(worker/d1d135eb-c935-4a81-923b-defd299778d1 (0)/3)] ERROR -- DirectorJobRunner: Failed to create/contact VM : #<Bosh::Director::RpcTimeout: Timed out pinging to 20fc959d-f865-4e7e-90b6-bfc2a3914fcd after 600 seconds>
```

_____

3. This one looks like the region we're deploying vms into lacked resources
```
E, [2019-06-05T18:20:32.001690 #27151] [task:1395072] ERROR -- DirectorJobRunner: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: Google Operation 'operation-1559758645188-58a979bfb563c-234956c4-ae3442fe' finished with an error: The zone 'projects/cf-concourse-production/zones/us-central1-f' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.
```

We saw this a lot on my previous team... It's def an iaas issue on this one, when it does happen, it happens continuously until GCP gets more resources.

**Comment by xtreme-james-thomson** [comment]
I am actually seeing a couple more common errors when trying to deploy:

1. Web not starting:
```
E, [2019-06-06T22:35:24.470628 #13647] [canary_update(web/853a2918-6f78-463c-aeec-ae622c3909a2 (0))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::AgentJobNotRunning: 'web/853a2918-6f78-463c-aeec-ae622c3909a2 (0)' is not running after update. Review logs for failed jobs: web>
```
^ This one we'd probably need to investigate if it happens again. Would probably need to ssh (either with bosh or through GCP) into the web vm and take a look at the logs.

2. Bosh can't acquire a lock
```
E, [2019-06-06T15:55:37.070935 #19780] [task:1396320] ERROR -- DirectorJobRunner: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "locks_name_key"
...
E, [2019-06-06T15:55:37.889511 #19780] [task:1396320] ERROR -- DirectorJobRunner: Failed to acquire lock for lock:release:concourse uid: 1a017e60-d89a-49f1-82fe-542c6657f8a7. Locking task id is 1396319
```
^ This has happened lots of times, we saw it a lot with bosh healthchecks on MP. There are lots of links out there for reasons it COULD happen, but I can't tell...

3. Undefined method `cloud`
```
E, [2018-09-29T06:00:00.379182 #3364] [task:1194100] ERROR -- DirectorJobRunner: undefined method `cloud' for Bosh::Director::Config:Class
```
^ We actually saw this on MP once upon a time, and we didn't really find a solution for it. Talked to someone from Bosh and they said they haven't seen it either. If this happens again frequently, the current Bosh team would probably be really interested in poking around. We should keep an eye open for it.
