### ISSUE TITLE
split topgun into separate track-owned jobs

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/ci#144]
ideas so far - we got interrupted several times with other things today and so haven't finished reading through all the test files.

@concourse/core-api:
Multiple ATCs Login Session Test
AWS SSM
Container scope
Credhub
Database secrets encryption

@concourse/runtime:
Rebalancing workers
Passing artifacts between build steps
An ATC with default resource limits set
Ephemeral Workers
A worker with a proxy configured

both:
ATC Shutting down
Garbage collecting build containers
Hijacked containers

@concourse/concourse-for-pcf:
BBR

**Comment by xtreme-sameer-vohra** [comment]
@pivotal-jamie-klassen should we close this as we have effectively done this ?

**Comment by pivotal-jamie-klassen** [comment]
@xtreme-sameer-vohra sure. The outstanding task, in my mind, was to make the different suites notify the right groups of people (the "track"s that owned them, rather than whoever last changed the code) in Slack or Discord when they failed. But I think this is gonna be tackled elsewhere anyway.
