### ISSUE TITLE
k8s-topgun Failing

### ISSUE THREAD

**Issue by taylorsilva** [concourse/ci#182]
k8s-topgun has been failing since Friday, September 27th. No concourse code changes occurred between the last passing build and the builds that followed it, all of them failing.

GKE cluster topgun run's on: `cluster-1`

There are two types of errors we're seeing.

### 1. Port forwarding fails

For a variety of tests we keep seeing port-forwarding fail.

One example, where `pod not found`:
```
STEP: Creating the web proxy
STEP: [1569964314.490616322] running: kubectl port-forward --namespace=topgun-swi-80011428 service/topgun-swi-80011428-web :8080
error: error upgrading connection: unable to upgrade connection: pod not found ("topgun-swi-80011428-web-7d4c8fb55b-6kk56_topgun-swi-80011428")
STEP: [1569964314.650369883] running: helm delete --purge topgun-swi-80011428
release "topgun-swi-80011428" deleted
STEP: [1569964315.270037413] running: kubectl delete namespace topgun-swi-80011428 --wait=false 
namespace "topgun-swi-80011428" deleted

• Failure [75.169 seconds]
Scaling web instances
/tmp/build/7f688b19/concourse/topgun/k8s/web_scaling_test.go:12
  succeeds [It]
  /tmp/build/7f688b19/concourse/topgun/k8s/web_scaling_test.go:22

  No future change is possible.  Bailing out early after 0.155s.
  Got stuck at:

  Waiting for:
      Forwarding
```

second example, `broken pipe`:
```
running wget -O- topgun-dp-10084543-web:8080/api/v1/info
Handling connection for 45551
initializing
failed
Handling connection for 45551
E1001 21:07:06.913259    7232 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:45551->127.0.0.1:51636: write tcp4 127.0.0.1:45551->127.0.0.1:51636: write: broken pipe
STEP: [1569964026.936306000] running: helm delete --purge topgun-dp-10084543
release "topgun-dp-10084543" deleted
STEP: [1569964027.552978992] running: kubectl delete namespace topgun-dp-10084543 --wait=false
namespace "topgun-dp-10084543" deleted



• Failure [75.527 seconds]
DNS Resolution
/tmp/build/7f688b19/concourse/topgun/k8s/dns_proxy_test.go:14
  different proxy settings
  /tmp/build/7f688b19/gopath/pkg/mod/github.com/onsi/ginkgo@v1.9.0/extensions/table/table.go:92
    Proxy Disabled, with short service name [It]
    /tmp/build/7f688b19/gopath/pkg/mod/github.com/onsi/ginkgo@v1.9.0/extensions/table/table_entry.go:46

    Expected
        <int>: 1
    to be zero-valued
```

third example, where port-forwarding breaks down in the middle of the test:
```
STEP: [1569963914.924532890] running: /tmp/gexec_artifacts279253227/g904034638/fly -t concourse-topgun-k8s-4 execute -c tasks/dns-proxy-task.yml -v url=topgun-dp-11517743-web.topgun-dp-11517743.svc.cluster.local:8080/api/v1/info
Handling connection for 38901
uploading topgun done.8KiB/s))
executing build 1 at http://127.0.0.1:38901/builds/1 
initializing
fetching busybox@sha256:dd97a3fe6d721c5cf03abac0f50e2848dc583f7c4e41bf39102ceb42edfd1808
7c9d20b9b6cd [======================================] 742.9KiB/742.9KiB
running wget -O- topgun-dp-11517743-web.topgun-dp-11517743.svc.cluster.local:8080/api/v1/info
Connecting to topgun-dp-11517743-web.topgun-dp-11517743.svc.cluster.local:8080 (10.11.241.215:8080)
wget: can't connect to remote host (10.11.241.215): Connection refused
failed
Handling connection for 38901
STEP: [1569963925.802273273] running: helm delete --purge topgun-dp-11517743
release "topgun-dp-11517743" deleted
STEP: [1569963926.385312796] running: kubectl delete namespace topgun-dp-11517743 --wait=false
namespace "topgun-dp-11517743" deleted

• Failure [61.513 seconds]
DNS Resolution
/tmp/build/7f688b19/concourse/topgun/k8s/dns_proxy_test.go:14
  different proxy settings
  /tmp/build/7f688b19/gopath/pkg/mod/github.com/onsi/ginkgo@v1.9.0/extensions/table/table.go:92
    Proxy Enabled, with full service name [It]
    /tmp/build/7f688b19/gopath/pkg/mod/github.com/onsi/ginkgo@v1.9.0/extensions/table/table_entry.go:46

    Expected
        <int>: 1
    to be zero-valued

    /tmp/build/7f688b19/concourse/topgun/k8s/dns_proxy_test.go:85
```

Fourth, failing in the middle of a test, example:
```
STEP: [1569920401.788959742] running: /tmp/gexec_artifacts116775232/g015069087/fly -t concourse-topgun-k8s-4 login -c http://127.0.0.1:39607 -u test -p test

logging in to team 'main'

Handling connection for 39607
Handling connection for 39607
target saved
STEP: [1569920401.954967737] running: /tmp/gexec_artifacts116775232/g015069087/fly -t concourse-topgun-k8s-4 workers --json
Handling connection for 39607
[]
STEP: [1569920411.992353678] running: /tmp/gexec_artifacts116775232/g015069087/fly -t concourse-topgun-k8s-4 workers --json
Handling connection for 39607
E1001 09:00:12.060585   10831 portforward.go:400] an error occurred forwarding 39607 -> 8080: error forwarding port 8080 to pod 2102f8dd698b355c7f0cc17193d227187229e3af46245ee35dae98bd3a77c0f4, uid : exit status 1: 2019/10/01 09:00:12 socat[174757] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
could not reach the Concourse server called concourse-topgun-k8s-4:

    Get http://127.0.0.1:39607/api/v1/info: EOF

is the targeted Concourse running? better go catch it lol

STEP: [1569920412.065531969] running: helm delete --purge topgun-bd-overlay-55649115
release "topgun-bd-overlay-55649115" deleted
STEP: [1569920412.527161837] running: kubectl delete namespace topgun-bd-overlay-55649115 --wait=false
namespace "topgun-bd-overlay-55649115" deleted

• Failure [42.312 seconds]
baggageclaim drivers
/tmp/build/7f688b19/concourse/topgun/k8s/baggageclaim_drivers_test.go:11
  GKE
  /tmp/build/7f688b19/concourse/topgun/k8s/k8s_suite_test.go:302
    ubuntu image
    /tmp/build/7f688b19/concourse/topgun/k8s/baggageclaim_drivers_test.go:36
      overlay
      /tmp/build/7f688b19/concourse/topgun/k8s/baggageclaim_drivers_test.go:46
        works [It]
        /tmp/build/7f688b19/concourse/topgun/k8s/baggageclaim_drivers_test.go:47

        Expected
            <int>: 1
        to be zero-valued

        /tmp/build/7f688b19/concourse/topgun/fly.go:100
```

### 2. Baggageclaim driver test fails

This one has been happening for most failures but it's not 100% either. When this specific test in topgun fails, it's **always** with this error, never the port-forwarding error. It happens for both the `cos` and `ubuntu` node selectors.
Doesn't happen in:
- https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/2107
- https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/2105
- https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/2103
- https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/2102 (bit overlay test failed here)
- https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/2101
- and a bunch of other one's..... **maybe this error is happening because something is really broken with our GKE cluster**

The test is
```
• Failure [302.169 seconds]

baggageclaim drivers

/tmp/build/7f688b19/concourse/topgun/k8s/baggageclaim_drivers_test.go:11
  GKE
  /tmp/build/7f688b19/concourse/topgun/k8s/k8s_suite_test.go:302
    cos image
    /tmp/build/7f688b19/concourse/topgun/k8s/baggageclaim_drivers_test.go:30
      btrfs
      /tmp/build/7f688b19/concourse/topgun/k8s/baggageclaim_drivers_test.go:72
        fails [It]
        /tmp/build/7f688b19/concourse/topgun/k8s/baggageclaim_drivers_test.go:73

        Expected
            <int>: 1
        to equal
            <int>: 0

        /tmp/build/7f688b19/concourse/topgun/k8s/k8s_suite_test.go:171

```

You can reproduce the error with this `helm install`
```
helm upgrade --install --force --wait --namespace topgun-btrfs-fails --set=web.livenessProbe.failureThreshold=3 --set=web.livenessProbe.initialDelaySeconds=3 --set=web.livenessProbe.periodSeconds=3 --set=web.livenessProbe.timeoutSeconds=3 --set=concourse.web.kubernetes.keepNamespaces=false --set=postgresql.persistence.enabled=false --set=image=concourse/concourse-rc --set=imageTag=latest --set=imageDigest=sha256:b61fbd930eefab9300744ca83e05a2f7bcb954ec341c996a7009014a50c8a374 --set=concourse.web.kubernetes.enabled=false --set=concourse.worker.baggageclaim.driver=btrfs --set=worker.replicas=1 --set=worker.nodeSelector.nodeImage=cos topgun-btrfs-fails /Users/pivotal/workspace/charts/stable/concourse
```
The worker pod fails to come up and goes into a crash loop. It's failing to create the btrfs volume. `kubectl logs` shows the following:
```
{"timestamp":"2019-10-01T21:15:25.924431822Z","level":"error","source":"baggageclaim","message":"baggageclaim.fs.run-command.failed","data":{"args":["bash","-e","-x","-c","\n\t\tif [ ! -e $IMAGE_PATH ] || [ \"$(stat --printf=\"%s\" $IMAGE_PATH)\" != \"$SIZE_IN_BYTES\" ]; then\n\t\t\ttouch $IMAGE_PATH\n\t\t\ttruncate -s ${SIZE_IN_BYTES} $IMAGE_PATH\n\t\tfi\n\n\t\tlo=\"$(losetup -j $IMAGE_PATH | cut -d':' -f1)\"\n\t\tif [ -z \"$lo\" ]; then\n\t\t\tlo=\"$(losetup -f --show $IMAGE_PATH)\"\n\t\tfi\n\n\t\tif ! file $IMAGE_PATH | grep BTRFS; then\n\t\t\tmkfs.btrfs --nodiscard $IMAGE_PATH\n\t\tfi\n\n\t\tmkdir -p $MOUNT_PATH\n\n\t\tif ! mountpoint -q $MOUNT_PATH; then\n\t\t\tmount -t btrfs $lo $MOUNT_PATH\n\t\tfi\n\t"],"command":"/bin/bash","env":["PATH=/usr/local/concourse/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","MOUNT_PATH=/concourse-work-dir/volumes","IMAGE_PATH=/concourse-work-dir/volumes.img","SIZE_IN_BYTES=10266165248"],"error":"exit status 32","session":"3.1","stderr":"+ '[' '!' -e /concourse-work-dir/volumes.img ']'\n++ stat --printf=%s /concourse-work-dir/volumes.img\n+ '[' 10266165248 '!=' 10266165248 ']'\n++ losetup -j /concourse-work-dir/volumes.img\n++ cut -d: -f1\n+ lo=/dev/loop4\n+ '[' -z /dev/loop4 ']'\n+ file /concourse-work-dir/volumes.img\n+ grep BTRFS\n+ mkdir -p /concourse-work-dir/volumes\n+ mountpoint -q /concourse-work-dir/volumes\n+ mount -t btrfs /dev/loop4 /concourse-work-dir/volumes\nmount: /concourse-work-dir/volumes: unknown filesystem type 'btrfs'.\n","stdout":"/concourse-work-dir/volumes.img: BTRFS Filesystem sectorsize 4096, nodesize 16384, leafsize 16384, UUID=226829f7-4ca4-41ed-8377-794b6095ef94, 114688/10266165248 bytes used, 1 devices\n"}}
{"timestamp":"2019-10-01T21:15:25.925165479Z","level":"error","source":"baggageclaim","message":"baggageclaim.failed-to-set-up-driver","data":{"error":"failed to create btrfs filesystem: exit status 32"}}
```

**Comment by taylorsilva** [comment]
To try and resolve the port-forwarding issue we did the following things today.

- Cleaned up all non-topgun pods on the GKE cluster. There were quite a few and the ubuntu node pool was nearly overloaded. It was already auto-scaled to the max it was allowed to auto-scale to (3 nodes)
- Increased the auto-scale size for the ubuntu node pool from 3 to 4
- Downgraded the GKE version from `1.14.0` to `1.13.10`. Did this for the `cos` node pool first and then the `ubuntu` node pool. Topgun is still failing with the port-forwarding error.

We do get the same port-forwarding errors when running topgun from our workstation in Toronto.

We did not look into the baggage claim error. Didn't notice it until EOD here.

**Comment by jomsie** [comment]
Good info Taylor!

It's weird that the flakes on this job are passing rather than failing! :P

**Comment by taylorsilva** [comment]
@xtremerui had an idea of the cause based on some discord messages. @pivotal-jamie-klassen tested it out and sadly saw no change.

```
[10:41 AM]
i also think that Rui's theory about k8s-topgun may be correct, because this looks prohibitively low: https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L1326
...
anyway i just hijacked into concourse/k8s-topgun and jacked it up to 512, and it's running smoothly so far
```

Found this related issue with `port-forward` that happens when there's a high transfer rate: https://github.com/kubernetes/kubernetes/issues/74551

We don't have a high transfer rate over the pipe though...

**Comment by taylorsilva** [comment]
I was playing around with `port-forwarding` from my workstation to a pod running concourse on the `topgun` cluster on GKE. The first time I ran the command I got this output:

```
kubectl port-forward topgun-pi-98467063-web-6c95748c68-pcdh9 8080:8080 -n topgun-pi-98467063
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E1004 14:13:00.125382   66254 portforward.go:372] error copying from remote stream to local connection: readfrom tcp6 [::1]:8080->[::1]:57513: write tcp6 [::1]:8080->[::1]:57513: write: broken pipe
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E1004 14:13:35.727857   66254 portforward.go:362] error creating forwarding stream for port 8080 -> 8080: Timeout occured
E1004 14:13:52.159867   66254 portforward.go:362] error creating forwarding stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E1004 14:14:29.016066   66254 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E1004 14:17:37.513215   66254 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
E1004 14:17:47.326371   66254 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080
```
The pipe kept breaking every `x` request that was sent over the pipe. In another terminal I was running `fly -t local teams` and every so often the command would get stuck waiting for a response and I would `ctrl+c` it. Sometimes it just worked and sometimes it didn't 😢 

```
~/w/c/t/k8s (master) $ fly -t local login -n main -u test -p test -c http://localhost:8080
logging in to team 'main'

^C⏎                                                                                                                                                         ~/w/c/t/k8s (master) $ fly -t local login -n main -u test -p test -c http://localhost:8080
logging in to team 'main'


target saved
~/w/c/t/k8s (master) $ fly -t local teams
^C⏎                                                                                                                                                         ~/w/c/t/k8s (master) $ fly -t local teams
name
main
~/w/c/t/k8s (master) $ fly -t local teams
name
main
~/w/c/t/k8s (master) $ fly -t local teams
^C⏎                                                                                                                                                         ~/w/c/t/k8s (master) $ fly -t local teams
name
main
~/w/c/t/k8s (master) $ fly -t local teams
name
main
```

I then walked away from my workstation and came back. I ran `port-forward` again and...

```
~/w/c/t/k8s (master) $ kubectl port-forward topgun-pi-98467063-web-6c95748c68-pcdh9 8080:8080 -n topgun-pi-98467063
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
```

No dropped connections or broken pipes. Accessing the web UI and running any fly command worked without any lag or connections dropping. `port-forward` was suddenly solid.

**Comment by xtremerui** [comment]
Is GKE our only option here? Could we set up a kubo cloud from another provider and try to verify both? If it turns out GKE cause this flakiness, we should find a stable version or just use another kubo cloud. I know we are all google now but if it affects productivity or just causing more resource then we should consider all other options.

**Comment by taylorsilva** [comment]
I failed to mention this; one of the first things we did was downgrade the GKE cluster. We initially downgraded the node pools in `cluster-1` to `1.13.10` (master node still on `1.14.6`).

After giving up on `cluster-1` we created the new `topgun` cluster running `1.13.7` (on master and all node pools) which is the current stable channel version of GKE. Same results.

To your main suggestion, using another k8's provider would work, GKE has just been easiest for us to use (until now 😒 ). We could just focus on the track of work we have were we want to run topgun on PKS.

**Comment by pivotal-jamie-klassen** [comment]
If kubectl port-forward just doesn't work anymore on GKE, we could also set up a proper ingress for the web service maybe?

**Comment by pivotal-jamie-klassen** [comment]
currently attempting to use `--set=web.service.type=LoadBalancer` in the helm deploys. Only challenge here is that we need to deploy twice - once to set up the loadbalancer and another to set `concourse.web.externalUrl` to whatever IP GKE assigns for the loadbalancer.

**Comment by pivotal-jamie-klassen** [comment]
@pivotal-bin-ju joined me for the second half of the day. We tried using the `deployFailingConcourseChart` helper in the btrfs test and that seemed to improve the second error class in @taylorsilva's initial description. Now we're just having trouble establishing parity between running the tests from our local machine vs running them on CI. @taylorsilva did you make any changes to the kube_config in vault when downgrading/re-creating the `cluster-1` cluster or creating the `topgun` cluster?

**Comment by pivotal-jamie-klassen** [comment]
EOD our modified k8s-topgun is still failing. We have seen errors about pulling `concourse/concourse` and we have seen errors about hitting our CPU limit. https://ci.concourse-ci.org/builds/7042603 was probably the smoothest run of the day.

**Comment by taylorsilva** [comment]
@pivotal-jamie-klassen I did change the kube_config in vault. I added onto it, I didn't delete anything. If you want to use cluster-1 then you should be able to switch the context by updating the kube_config in vault.

**Comment by pivotal-bin-ju** [comment]
Topgun with `Loadbalancer` seems very slow. so I have to go back to `port-forwarding`. The `port-forwarding` is going to create a tunnel between localhost to node, then node to pod(correct me if I am wrong). What I did for investigating this issue:
1. Deploy application in different node, setup port-forwarding, then curl for 100 times. I can not see the problem with the nodes in `cluster-1`.
2. Did the topgun test against older version of charts. We could still see the error.
3. Comment out the `cleanup`, `port-forwarding` to web pod. We could successfully `port-forward` to the web pod.

The thing I am currently continuing is add `sleep` after 'waitAllPodsInNamespaceToBeReady`. I thought there is a possibility that the access to concourse web happened too early, even the pod is ready, but concourse is not ready to serve.

**Comment by pivotal-bin-ju** [comment]
@clarafu and I today:
1. added `for` loop for concourse status checking at the end of `startPortForwardingWithProtocol` to ensure concourse is ready to serve. But, we can still see the `Connection refused` error message.
2. switched to  branch `k8s-topgun-resilience`. Last time I found the code fix (didn't dig into it) for function `baggageclaimFails` This test hanged for very long time. I thought that may be the reason slowed down topgun test. But after reverting the change, it is still slow.
3. Focus on `baggageclaim drivers` test and run many times. But I can not see the error. Is it caused by parallel running of topgun test? or some case did something make the test environment unstable? or the gke cluster `cluster-1` is unstable.

**Comment by jomsie** [comment]
> I found all most all the errors is from the second polling of `getWorkers`:
> 
> ```
> Eventually(func() []Worker {
> 		return getRunningWorkers(fly.GetWorkers())
> 	}, 5*time.Minute, 60*time.Second).
> 		ShouldNot(HaveLen(0))
> ```
> 
> I doubt there is a turbulence when the call `fly.GetWorkers()` returns empty result set, and worker is not connected to web at that moment. What I am doing is set timeout to 5 minutes, and the polling interval to 1 minute.
> 
> Now only one timeout case after helm install. doing now test to verify the hypothesis.

good sleuthing bin!

**Comment by taylorsilva** [comment]
We tried wrapping the assertions in `Eventually` rather than `Expect` in a few places, and we're having better luck now with flaky tests retrying:

```go
Eventually(func() int {
	sess := fly.Start("execute", "-c", "tasks/dns-proxy-task.yml", "-v", "url="+c.addressFunction())
	<-sess.Exited
	return sess.ExitCode()
}, 5*time.Minute, 1*time.Second).Should(Equal(statusCode))
```

Here's the output we're seeing, with evidence that the tests are retrying after a "pipe failed" error (we added a `runCount` counter to observe how many retries it was making):

```
Running in parallel across 4 nodes

SSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
run count:  1
uploading topgun done
executing build 1 at http://127.0.0.1:64313/builds/1
initializing
fetching busybox@sha256:dd97a3fe6d721c5cf03abac0f50e2848dc583f7c4e41bf39102ceb42edfd1808
7c9d20b9b6cd [======================================] 742.9KiB/742.9KiB
initializing
unexpected end of JSON input

when parsing resource response:


errored
run count:  2
uploading topgun done
executing build 2 at http://127.0.0.1:64313/builds/2
initializing
fetching busybox@sha256:dd97a3fe6d721c5cf03abac0f50e2848dc583f7c4e41bf39102ceb42edfd1808
7c9d20b9b6cd [======================================] 742.9KiB/742.9KiB
running wget -O- topgun-dp-63248439-web:8080/api/v1/info
wget: bad address 'topgun-dp-63248439-web:8080'
failed
•
```

**Comment by taylorsilva** [comment]
We have k8s-topgun in a state where we see two types of errors now.

kubectl fails to port-forward immediately:
```
running: kubectl port-forward --namespace=topgun-swi-5252704 service/topgun-swi-5252704-web :8080
error: error upgrading connection: error dialing backend: EOF
```
and same from helm:
```
running: helm delete --purge topgun-bd-btrfs-6986744
Error: forwarding ports: error upgrading connection: error dialing backend: EOF
```

After 4 runs, it passed 3 of them. 75% is good enough for now. Going to make a PR with these changes.

**Comment by pivotal-jamie-klassen** [comment]
@taylorsilva I just tried something kinda cool. Using `/concourse/main/concourse/kube_config` from vault as `~/.kube/config`, I ran
```
$ kubectl run -i --tty --attach --pod-running-timeout=5m topgun --image concourse/unit --env CONCOURSE_CHART_DIR=/go/charts/stable/concourse --env CONCOURSE_IMAGE_NAME=concourse/concourse --env KUBE_CONFIG="$(cat ~/.kube/config)"
```
and in the resulting shell I ran
```
$ git clone https://github.com/concourse/ci
$ git clone https://github.com/concourse/concourse
$ git clone https://github.com/helm/charts
$ ci/tasks/scripts/k8s-topgun
```
and the tests ran properly. I'm curious about scripting this approach. What would be especially appealing about running the tests from inside the k8s cluster is that it would remove the need for `kubectl port-forward` - instead we could just connect to the desired pods by their k8s service name.

**Comment by pivotal-jamie-klassen** [comment]
So that we don't forget about it, @cirocosta and @matthewpereira were talking today about having a long-lived worker living inside the k8s cluster which would also be able to access any helm-deployed clusters without any kind of proxying.
