### ISSUE TITLE
release pipelines use `cluster-1`, rather than `topgun` gke cluster

### ISSUE THREAD

**Issue by cirocosta** [concourse/ci#195]
Hey,

A little bit before getting https://github.com/concourse/concourse/pull/4643 in, we got a cluster (`topgun`) created in GKE, having node pools that make more sense than before (high cpu, with autoscaling set).

It turns out that we never changed the cluster that k8s-topgun target in the release pipelines though.

As a result, we're now with the clusters, while in practice, we could have just one.

Thanks!

(not necessarily related, but could be done together w/ https://github.com/concourse/prod/issues/36)

**Comment by jomsie** [comment]
Wow, so the new GKE cluster is not being used by anything? Good snag for sure!
