### ISSUE TITLE
release pipelines don't bump `concourse-bosh-deployment`

### ISSUE THREAD

**Issue by taylorsilva** [concourse/ci#198]
In the main pipeline we run this task: https://github.com/concourse/concourse-bosh-deployment/blob/master/ci/bump-versions.yml

We don't run this task in our release pipelines. We're trying to leverage the [concourse-bosh-deployment] repo in [our docs] more and having minors correctly tagged will help keep our docs accurate. 

As a side-note, for some reason we have tags for each minor for `5.5.x` and don't have any of the minors tagged for `5.2.x`. Each tag appears to have been made by CI, not sure how this happened though.

[concourse-bosh-deployment]:https://github.com/concourse/concourse-bosh-deployment/
[our docs]:https://github.com/pivotal/docs-concourse-pcf/pull/6

**Comment by xtreme-sameer-vohra** [comment]
+1 still an issue and occurred with the v5.7.2 release

**Comment by pivotal-jamie-klassen** [comment]
@taylorsilva I suspect those 5.2.x and 5.5.x tags may have actually been created by the main pipeline during periods of time when 5.2.x and 5.5.x were the latest minors, respectively. Not totally sure, but it's a possible explanation

**Comment by xtreme-sameer-vohra** [comment]
FYI  @scottietremendous 
Something to keep in mind if we need to do a patch release
