### ISSUE TITLE
move PR pipeline and checks over to new CI

### ISSUE THREAD

**Issue by deniseyu** [concourse/ci#211]
PR checks still run on old CI! We should move them to new CI. But first we need to spin up the PR pipeline on new CI.

**Comment by xtremerui** [comment]
We will need to first deploy pr workers in new CI.

**Comment by deniseyu** [comment]
For visibility:

- [ ] Provision new workers in separate nodepool with antiAffinity enabled
- [ ] Understand how networking policies work for pod-to-pod communication across namespaces
- [ ] Enable networkPolicy at cluster level
- [ ] Create network policies to isolate PR workers from normal workers
- [ ] Roll out change across all nodepools in production cluster 🤞 
- [ ] Profit

**Comment by cirocosta** [comment]
https://github.com/concourse/hush-house/pull/75
