### ISSUE TITLE
`yarn-benchmark` step in `unit` job in `prs.yml` always merges PR to master

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/ci#213]
Not all PRs are made against master. Ideally this task will run the benchmarks against the result of merging the PR with its actual base branch - failing that, it's probably OK to skip the check for non-master-based PRs.

here is an example: https://ci.concourse-ci.org/builds/7242704

**Comment by zoetian** [comment]
Turns out we misunderstood https://github.com/concourse/concourse/pull/4785#issuecomment-555578080, and our PR resource is working properly.
