### ISSUE TITLE
k8s-topgun needs helm/stable/postgresql and helm/table/prometheus

### ISSUE THREAD

**Issue by xtremerui** [concourse/ci#222]
With the changes done in https://github.com/concourse/ci/commit/30e5721a20ad7574091ae0e6691704f79cf9642c, now `helm` contains only concourse-chart.

However in `k8s-topgun` job there are tests relying on [postgresql-chart](https://github.com/concourse/concourse/blob/db19f87d078278c32e71f962c0b32d0ceb2227d6/topgun/k8s/external_postgres_test.go#L18) and [prometheus-chart](https://github.com/concourse/concourse/blob/db19f87d078278c32e71f962c0b32d0ceb2227d6/topgun/k8s/prometheus_test.go#L29), which is now [broken](https://nci.concourse-ci.org/teams/main/pipelines/release-5.5.x/jobs/k8s-topgun/builds/5) in release/5.5.x pipeline, for example.

Do we need also `concourse/postgresql-chart` and `concourse/prometheus-chart` or we pull down those from `github.com/helm/charts` still?

**Comment by cirocosta** [comment]
hmmm that's interesting, I thought we had covered that 🤔  

https://github.com/concourse/ci/blob/a59f75890e98f2fd4fd61d5483b39a851b9f83de/pipelines/concourse.yml#L485-L490

https://github.com/concourse/ci/blob/a59f75890e98f2fd4fd61d5483b39a851b9f83de/pipelines/release.yml#L464-L467

**Comment by cirocosta** [comment]
(whops, wrong button)

**Comment by cirocosta** [comment]
ooooh, the resource config is wrong:

https://github.com/concourse/ci/blob/a59f75890e98f2fd4fd61d5483b39a851b9f83de/pipelines/release.yml#L1224-L1236

**Comment by cirocosta** [comment]
`helm-charts` should point to `helm/charts`
