### ISSUE TITLE
Use `set_pipeline` step instead of `reconfigure`

### ISSUE THREAD

**Issue by cirocosta** [concourse/ci#255]
Hey,

We just shipped [`set_pipeline`], let's make use of it 😁  

With it, we can remove the use of the `concourse-pipeline-resource` resource type 

https://github.com/concourse/ci/blob/59bedba87605d92272ae2a7b525004d5554e0792/pipelines/reconfigure.yml#L1-L5

[`set_pipeline`]: https://concourse-ci.org/set-pipeline-step.html

Thanks!

**Comment by pivotal-jamie-klassen** [comment]
almost there with https://github.com/concourse/ci/commit/6bdef4af5e9a1ee8951f8553fb38334e19f04a4b, but still need to remove that resource type.
