### ISSUE TITLE
have a `testflight-containerd` job/step

### ISSUE THREAD

**Issue by cirocosta** [concourse/ci#267]
Given that `testflight` ends up forcing a lot of container-related operations to
occur, it'd be great to have `testflight` continuously running against a
`containerd`-based worker.

As we'd not be fully commited to *just* containerd yet (still experimental), it
seems reasonable to me to have a `testflight-containerd` job / step.

refs:
- https://github.com/concourse/ci/blob/master/tasks/scripts/testflight
- https://github.com/concourse/ci/blob/master/tasks/docker-compose-testflight.yml

**Comment by taylorsilva** [comment]
It exists in the main pipeline too now: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight-containerd/

**Comment by taylorsilva** [comment]
and the release pipeline too: https://ci.concourse-ci.org/teams/main/pipelines/release-6.0.x/jobs/containerd-integration
