### ISSUE TITLE
images/unit: update the version of BOSH cli

### ISSUE THREAD

**Issue by cirocosta** [concourse/ci#278]
As pointed out by @jtarchie (https://github.com/concourse/concourse/pull/5237#issuecomment-591679013), the version that we're embedding in the `unit` image is not very up to date

https://github.com/concourse/ci/blob/d041c816ed825cc1b601ca7fa2dcb03ed52814f7/dockerfiles/unit/Dockerfile#L44-L47

and that can be a problem with regards to how the formatting changed.

Ultimately, the formatting problem could be dealt with usign somethign like` --json` (which we could then parse), but that'd be for another issue - the scope of this is making sure we're not far behind on major version bumps.

**Comment by pivotal-jamie-klassen** [comment]
FWIW depending on priority/pressure, we could use a github-release resource to track this and always track the latest.

**Comment by vito** [comment]
stale bot pls
