### ISSUE TITLE
author README(s)

### ISSUE THREAD

**Issue by mdb** [concourse/ci#28]
Hey all - Thanks for your great work on Concourse and thanks for publishing Concourse's `ci` automation to GitHub. As a user, enthusiast, and potential contributor, I'd love to learn more about what's happening throughout this repo. A `README` -- or even multiple `README`s, if needed -- could help. Thanks!

**Comment by xtreme-james-thomson** [comment]
@pivotal-jamie-klassen @vito @cirocosta would love some extra eyes/context on this readme! 
It's rough and early, but would be nice to get it in a good state.

**Comment by vito** [comment]
@jomsie Anything's better than nothing! Looks fine to me. :slightly_smiling_face:

**Comment by mdb** [comment]
Thanks @jomsie ! I'll close this issue, as your contribution addresses my core concern 👍
