### ISSUE TITLE
helm-prs/lint-and-install-test can't run against the same PR twice

### ISSUE THREAD

**Issue by jamieklassen** [concourse/ci#282]
Adding new commits to a PR or re-running testing for a PR feel like pretty natural use cases that would be good for the helm-prs pipeline to tolerate.

PR 79 was tested successfully here:
https://ci.concourse-ci.org/teams/main/pipelines/helm-prs/jobs/lint-and-install-test/builds/27
but when a new commit was pushed to the same PR, it fails, stating that the namespace associated with the PR already exists:
https://ci.concourse-ci.org/teams/main/pipelines/helm-prs/jobs/lint-and-install-test/builds/28#L5e615083:25

I haven't thought through the consequences here, so I'm not sure what solution to suggest, but I can think of two alternatives:
1. Attempt to delete the release before testing, in a manner similar to k8s-smoke on the main pipeline:
https://github.com/concourse/ci/blob/5b1bdfd/pipelines/concourse.yml#L447-L453

2. Not sure what options are available to do this (some kind of `--force` flag for `helm` maybe?), but maybe the chart installation could continue even if some associated resources already exist.

**Comment by xtreme-sameer-vohra** [comment]
Hey @pivotal-jamie-klassen 
I ended up solving the issue by also cleaning up the namespace - https://github.com/concourse/ci/pull/318
Does that suffice ?

**Comment by pivotal-jamie-klassen** [comment]
That approach makes sense. Will it still delete the namespace if the test fails?
