### ISSUE TITLE
Integrate drills into the branch pipeline flow

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/ci#29]
* environment creation should be trivial - an easy way to skip any testing
  * see about deploying a dev release rather than committing blob references on the bosh-release repo
  * such a job should live alongside the default testing flow, deploying to the same bosh environment but always using the latest code from the experimental branch with no passed constraints.
* metrics should be automatic
* upgrade tests should be easy to run?

**Comment by pivotal-jamie-klassen** [comment]
At the end of day, we almost got there, but discovered a few things:
1. currently the `hoist-linux-dependencies` step requires `unit-image`, but this might be overkill
1. `bosh-setup-env` needs to run first to set up the cloud config
1. the `create-dev-release` step seems to check out the release repo from whatever version the backing resource says, which might screw up our ability to use `bosh-bump` without actually pushing a commit. Maybe we can get around this by copying the release to a different directory before running `create-dev-release`? 🤷‍♂

**Comment by pivotal-jamie-klassen** [comment]
something about this issue is starting to smell funny to me. Briefly, I have this feeling that the runtime and core tracks are always going to have a more solid grasp on their use case than we are, so there doesn't seem to be a strong benefit to putting this work in a separate track. @vito does that make sense?

**Comment by vito** [comment]
@pivotal-jamie-klassen Sure, we can just have the tracks facing these challenges be the same ones to address them.
