### ISSUE TITLE
don't gate release on Wings deploy

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/ci#30]

**Comment by xtreme-james-thomson** [comment]
I'm assuming this would be as _easy_ as adding a time resource to the `bosh-wings-deploy` job?
So anything that passed prod deploy would go right into wings!

**Comment by cirocosta** [comment]
Hey,

I remember one argument around *not* deploying to Wings constantly was that we could then catch problems (like leaks) that only occurs after you have Concourse running for a long time. 

That might be something to take into consideration too 🤔

**Comment by xtreme-james-thomson** [comment]
That's a good point, should Prod be continuous deployed for our own quick feature tests and Wings be a longer living env for monitoring and testing?

Could use some discussion!

**Comment by pivotal-jamie-klassen** [comment]
## what is Wings for?
https://medium.com/concourse-ci/earning-our-wings-a0c307fa73e6
* **Better understand the 'operator' persona and the needs of an operator when running a multi-tenant Concourse**
* Observe Concourse performance "at scale"
* Build out a set of recommendations for operationalizing, monitoring and logging a Concourse installation
* Identify common support issues and their solutions

## why deploy more often?
@pivotal-jamie-klassen:
> ... weekly wings deploys to get us closer to continuous delivery and make shipping less of an event.

This doesn't relate to the purpose of wings. Nowhere above do we say that Wings should be a gate in our release process.

@cirocosta:
> ... it forces us to making wings deployments more smooth 

Smoother Wings deploys are definitely desirable, but this impedes our ability to understand the operator persona. Real operators can't deploy intermediate versions between releases, and it's possible that activity accumulating between deploys can make individual deploys less smooth.

@clarafu:
> ... it would push us to want to make upgrades smoother and we would be more cautious about what we PR in to master in order to keep it in a completely working and shippable state.

Unfortunately the more we deploy to wings, the less realistic the deploys become. I think the real fix here is more realistic upgrade testing. Two ideas that come to mind:
* run upgrade tests on PRs
* take the schema at the last release and randomly insert data, asserting that the migration to the latest version was resilient, even without any data integrity guarantees provided by the ATC

## why not?
@cirocosta:
> we could then catch problems (like leaks) that only occurs after you have Concourse running for a long time

## conclusion

I think we should not deploy to wings more than once per release, as this keeps it a useful tool for understanding the operator persona. However, if gating our releases on wings deploys is hampering our ability to release, let's retool this issue to be about deploying to wings after/as part of each release.

**Comment by clarafu** [comment]
That's a really good point, with that original goal of wings in mind it doesn't make sense to make wings deploys be weekly.

**Comment by cirocosta** [comment]
That's an amazing way of structuring the conversation! thank you for the effort on doing it!
