### ISSUE TITLE
Lint & Install script failed when re-run on the same PR

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/ci#317]
# Run 1 - passed
![Screen Shot 2020-05-08 at 9 44 30 AM](https://user-images.githubusercontent.com/1062564/81417311-9e538780-9110-11ea-8e45-e75ca97d4085.png)
 
# Run 2 - failed 
`Error: release pr-102-40f5c8 failed: namespaces "pr-102-40f5c8-main" already exists`

![Screen Shot 2020-05-08 at 9 44 49 AM](https://user-images.githubusercontent.com/1062564/81417316-a01d4b00-9110-11ea-9357-a8c65a54c0cf.png)

Besides cleaning up the helm deployment, we need to cleanup the namespace as well.

**Comment by xtreme-sameer-vohra** [comment]
Old namespaces for PRs are still around
![Screen Shot 2020-05-08 at 9 48 39 AM](https://user-images.githubusercontent.com/1062564/81417673-276abe80-9111-11ea-9187-91ba0a4ee636.png)

**Comment by cirocosta** [comment]
this seems a lot like a duplicate: https://github.com/concourse/ci/issues/282

**Comment by xtreme-sameer-vohra** [comment]
Woa, yes :)
