### ISSUE TITLE
epic: git-flow

### ISSUE THREAD

**Issue by jamieklassen** [concourse/ci#319]
**terminology**: `cbr` = `concourse-bosh-release` and `cbd` = `concourse-bosh-deployment`.

This repo has two important pipeline templates: `pipelines/concourse.yml` (used, broadly, for testing and shipping the code on the `master` branch of `concourse/concourse`), and `pipelines/release.yml` (very similar, but for `release/x.x.x` branches). There is a lot of duplication between these two templates - they both follow the same basic flow:

### how to test & ship concourse

1. run the unit tests and build a base dev layer including the bundled resource types
2. build a docker image from the dev layer and test upgrading, downgrading, testflight & watsjs against it in various configurations (postgres 9.5, containerd enabled, etc)
3. build the RC tarballs (linux/linux-ubuntu/darwin/windows) with a "final version", deploy it as a systemd service on a GCP VM and smoke-test it
4. package the linux/linux-ubunu RC tarballs into RC docker images
5. (`concourse.yml` only) smoke-test that RC image by following (a slight variation of) https://concourse-ci.org/quick-start.html
6. plug that RC image into the helm chart and run smoke tests, then topgun tests with latest (or pinned) versions of postgres and prometheus
7. upload the linux-ubuntu and windows RC tarballs to GCS (the `concourse-bosh-blobs` bucket) and bump the relevant branch on `concourse-bosh-release` to reference them
8. create a BOSH dev release, run it through smoke tests, then topgun tests with latest (or pinned) versions of bpm/bbr/postgres/uaa/credhub.
9. SHIPIT: Fan in from 3, 6 and 8.
10. tag the source commit for the RC tarballs, upload them as a github release.
11. rebuild the docs site so it points to the latest (by semver) release, which may have just changed.
12. Re-tag the RC image appropriately on dockerhub.
13. Bump the imageTag and patch version in the chart, commit it.
14. Do a `bosh finalize-release` and commit/tag the result on `cbr`.
15. Bump update the versions mentioned in `cbd` with whatever passed 8 and commit/tag.
16. (`release.yml` only) Upload bosh release tarball to Tanzu network
17. (`release.yml` only) Build enterprise helm chart tarball, upload to Tanzu network
18. (`release.yml` only) Explode the tarballs from 16 & 17, locate the source code for all of them and generate an open source license disclosure. _note_: this can take a _long time_.
19. (mostly done manually) Update enterprise release notes/docs at https://docs.pivotal.io/p-concourse.

* There are a lot of steps up there, and a lot of them are near-identical in both templates, which means a lot of them run the risk of silently diverging and then breaking the next time you need them!
* What has been especially problematic is that we have set the precedent that the first patch of each minor release `M.m.0` should be shipped using the `concourse.yml` template, and then a `release/M.m.x` branch and associated `release-M.m.x` pipeline should be manually created. Then any subsequent patches should be shipped with the new branch/pipeline. An unfortunate side effect of this is that both templates need to be kept working because we count on both of them for releases, each used roughly as often.

It occurred to @scottietremendous that it would be nice to upload 6.1.0 to Tanzu network, and the current branching strategy forbids this -- 6.1.0 is the first patch for a minor line, and so must be shipped from `master` with `concourse.yml`, but only `release.yml` knows how to upload to Tanzu network! So we came up with an idea.

### short term - no shipping from master

We could revise the above approach by 
* start the `version` resource in `release.yml` at `M.m.0-rc.1` instead of `M.m.1-rc.1`.
* remove steps 9+ from `concourse.yml`
* when you're almost ready to release, create a `release/M.m.x` branch from `master` and create the `release-M.m.x` pipeline. As you approach the release, push changes to this `release/M.m.x` branch and use the `release-M.m.x` pipeline for testing. Then follow steps 9+ as usual.
* _optional_ instead of having a (potentially-)reusable branch/pipeline for a whole minor line, we could have a branch named for the specific patch (like `release/6.1.0` instead of `release/6.1.x`) which gets merged back to master when the release is cut. This is git-flow-like, but if we do it we will need to understand that LTS minors will be different, with their own long-lived branches. I'd vote that we call those `support/*`, i.e. `support/5.5.x` or `support/6.1.x` (if we decide 6.1 is a candidate for LTS).

### long term - decouple testing & shipping

This is definitely an improvement, but there still all the duplicated steps 1-8 between the two templates -- although those jobs run much more often, so we'd be in a better position. Can we remove the duplication there, too? I think so. The idea would be to split up the shipit job so that it would just create a tag for the source code for a release, and "promote" (by renaming or adding some kind of GCS metadata?) the relevant artifacts (binary tarballs & docker image) output from the testing.

Then another pipeline would watch the tags across all branches of `concourse/concourse` using the `tag_filter` feature of the git resource, and whenever it saw a tag, it would start the following (reduced) pipeline:
1. Re-build the linux/linux-ubuntu/windows/darwin tarballs from the tagged source code, setting the version (specified in the tag name) at build time. Other build-time dependencies should be retrieved from the "promoted" artifact (i.e. explode the tarball, rebuild the `concourse` binary and then archive everything together again). Upload these finalized tarballs as a github release.
1. Upload these finalized tarballs to GCS, point the bosh-release source code to them, do a `bosh finalize-release` and commit to `cbr`. Upload the bosh release tarball to Tanzu network. **question** how to recover the versions of bpm/bbr/postgres/uaa/credhub that were used in testing and update `cbd` appropriately?
1. Re-build the docker image, packaging the re-built tarball, and push/tag it on dockerhub. Point the helm chart to this new image & bump the helm chart versions, commit it, run `helm package` and upload to the `concourse-charts` bucket.
1. Re-build the enterprise helm chart tarball and upload it to Tanzu network.
1. Explode the helm chart and bosh release, figure out all the source codes and prepare for generating open source license disclosures.

**Comment by jamieklassen** [comment]
A consequence of the "no shipping from master" is that the `version` semver resource in the `concourse.yml` template becomes less meaningful. Perhaps we could remove it, and any artifacts output by this template could be tagged in a non-semver fashion ('dev' builds instead of 'RCs').

**Comment by clarafu** [comment]
A few notes that I pointed down during our meeting about our next steps to improving our release process:

- Implementing releasing test suite for our release pipelines
- Releasing should only happen from release pipelines
- Master pipeline is a pure testing pipeline (remove the `ship-it` job from master)
  - possibly producing nightly release candidates from the master pipeline to allow users that want to use cutting edge Concourse technology (the release pipelines will produce rcs of a specific version of Concourse, but the rcs would only be available after the release pipeline is created) 
- Create the release pipeline when we decide what is the next release (major/minor, etc) during rpm
  - what the process might look like if we want to release every 3 weeks: we can decide what features/bugs will be included in the next release at the release planning meeting for the last week, decide whether it will be a major or minor version bump and then create the release branch.
- Figure out a separate process for long lived **support** release pipelines. Typically we would merge release branches back into master when the version is released, but support release branches will need to stay around for however long that version will be supported.
