### ISSUE TITLE
merge conflicts in release notes suck

### ISSUE THREAD

**Issue by jamieklassen** [concourse/ci#329]
## Problem

Sometimes when I'm reviewing PRs I get frustrated because it feels like every time a PR gets merged, every _other_ PR now has merge conflicts in `release-notes/latest.md`. Especially if there's a time difference between the PR author and reviewer, silly conflicts like this can cost a full day of feedback where the whole conversation is "rebase please". Can we avoid this toil?

### one file per note

The first thing that comes to my mind is this: Rather than having the `release-notes` folder contain a single `x.y.z.md` file for each release, have a subfolder for each release, and in each folder, every release note lives in a separate file.

Instead of:

```
release-notes
├── latest.md
├── v6.1.0.md
├── v6.0.0.md
└── v5.8.0.md
```

We could have:

```
release-notes
├── latest
│   ├── boring-bugfix.md
│   └── cool-new-feature.md
└── v5.8.0
    └── evanchaoli-completed-the-roadmap.md
```

### consequences

The automation that [builds](https://github.com/concourse/ci/blob/master/tasks/build-release-notes.yml) the [release notes](https://github.com/concourse/ci/blob/master/tasks/scripts/build-release-notes) would need to be updated appropriately. Probably it would just concatenate all the markdown files in the version directory in question.

I'd rather have some testing (per #328) in place before making this change "live".

**Comment by aoldershaw** [comment]
This makes total sense to me - the order of release notes should come down to the release anchor anyway, so I can't really see any reason to have everything in a single file

Also `evanchaoli-completed-the-roadmap.md` 😁

**Comment by jamieklassen** [comment]
Publicly admitting to my subtly-pejorative use of the word "just" in

> Probably it would _just_ concatenate all the markdown files in the version directory in question.

If you're gonna concatenate things you still have to decide how to sort them, as @aoldershaw has hinted. To truly automate this might involve some subtle encoding. Maybe something like a filename pattern:

```
<change type>-<priority>-<human-readable slug>.md
```

where `<change type>` is `fix` or `feature`, `<priority>` is a number, say 0-5, and `<human-readable slug>` is some helpful shorthand like `evanchaoli-completed-the-roadmap`. In this case, we might get the content of files like `feature-5-global-resources.md` appearing higher in the final release notes than files like `fix-0-helptext-typo.md`.

Another completely different option would be to involve some automation that queries the GitHub API, looks up the PR that introduced the release note and sorts it based on tags on that PR.
