### ISSUE TITLE
bin-smoke flakes because of xip.io

### ISSUE THREAD

**Issue by jamieklassen** [concourse/ci#338]
## Problem - needless red builds

Examples:

* [bin-smoke #186](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke/builds/186)
* [bin-smoke-containerd #56](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke-containerd/builds/56)
* [bin-smoke #191](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke/builds/191)
* [bin-smoke-containerd #64](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke-containerd/builds/64)

In each of these cases, it looks like the initial `/api/v1/info` health check succeeds but then the DNS lookup fails some time after that.

## Solution - remove dependence on xip.io

We're using xip.io because LetsEncrypt will only provide a cert when you give it a DNS name. Rather than have to work around the unreliability of xip.io, I suggest we use our own DNS entries for the smoke environments. Something like `<job name>.<pipeline name>.concourse-ci.org`. Whatever we choose, it is crucial that each smoke VM have a **unique** DNS name (i.e. bin-smoke and bin-smoke-containerd can't end up with the same name). 

Dependencies of this strategy include:
* Deciding how the DNS name is to be determined, respecting the "uniqueness" property described above - we should be able to use some combination of the terraform workspace and the `USE_CONTAINERD` var.
* adding the DNS entry to the terraform config, similar to:
https://github.com/concourse/hush-house/blob/d381bfc143bef7dbb86790cab3e96fb5102c334a/terraform/main.tf#L30-L38
* updating the systemd config template:
https://github.com/concourse/ci/blob/5c2f5d23f348156d837626f726ffb8e1ad12e388/deployments/smoke/systemd/smoke-web.conf.tpl#L7
* updating the terraform config (to supply a DNS name instead of just the IP address):
https://github.com/concourse/ci/blob/5c2f5d23f348156d837626f726ffb8e1ad12e388/deployments/smoke/smoke.tf#L122
* while we're here, maybe pay down some tech debt? I think we could use a `TF_VAR_`-prefixed environment variable to pass the `USE_HTTPS` param, as described in https://github.com/concourse/ci/commit/25e9e03f183d31bb9234f880a5381c06f1e9d339

**Comment by jamieklassen** [comment]
it happened again https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke-containerd/builds/95

**Comment by xtreme-sameer-vohra** [comment]
There is also another [alternative](https://nip.io/) we can try to see if its more reliable than xip
