### ISSUE TITLE
enable `across` step on CI, use it for testflight/bin-smoke permutations

### ISSUE THREAD

**Issue by jamieklassen** [concourse/ci#369]
blocked on concourse/concourse#5887, which I just approved.

Let's see if we can't collapse the outlined sections of our development pipeline using the magic of build matrices:
<img width="990" alt="Screen Shot 2020-08-17 at 5 48 08 PM" src="https://user-images.githubusercontent.com/22056320/90447777-00c60780-e0b2-11ea-8ecb-af9820a6a299.png">

**Comment by jamieklassen** [comment]
The stale bot scared me, so I did some work on this this morning -- now we have a single testflight job which matrixes across the worker runtime and postgres version!

**Comment by zoetian** [comment]
Dev Notes: 

@chenbh and I picked up this issue. However, we did not realize the work on branch `issue/369`, we created a temporary branch `issue/369-bin-smoke` for the bin-smoke only. We will also port over the changes for `testflight/prs` and `testflights/release-pipelines` tomorrow.

**Comment by chenbh** [comment]
This was done
