### ISSUE TITLE
Run PKS tests in the Main Pipeline

### ISSUE THREAD

**Issue by scottietremendous** [concourse/ci#40]
[@cirocosta here]:

**Summary**

In order to continuously run [topgun tests][pks] for [PKS][pks-docs], we will
need to target PKS when running our end-to-end tests in the [main pipeline][pipeline]. 

This will include:

- Having a task that tests properly authenticating and targeting PKS
  - note.: the vSphere environment is not something that is available everywhere
    - only Pivotal networks can reach it.
- Have the credentials available to the Concourse installation
  - see [Adding and reading secrets in Vault][vault]

**Acceptance Criteria**

- [ ] k8s-pks-topgun job is green

**Extra context**

To know more about the PKS environment that the team has available to it, please
check out [PKS on Toolsmiths vSphere][pks-env].

[pks-docs]: https://docs.pivotal.io/runtimes/pks/1-4/
[topgun]: https://github.com/concourse/concourse/tree/master/topgun/k8s
[pipeline]: https://ci.concourse-ci.org/teams/main/pipelines/concourse
[pks-env]: https://github.com/pivotal/concourse-ops/wiki/PKS-on-Toolsmiths-vSphere
[vault]: https://github.com/pivotal/concourse-ops/wiki/Adding-and-Reading-Secrets-in-Vault

**Comment by taylorsilva** [comment]
### Dev Notes

Thinking about how we're going to get this to run in CI and this is our current idea.

Deploy a single worker vm onto the `bulbasaur` vsphere environment. From `prod` we can tag and then target the worker to run topgun on pks.

When we need to update the worker we can send a task to it that will target it's bosh director and update it's deployment manifest, similar to how prod updates itself by targeting it's bosh director.

**Comment by YoussB** [comment]
### Dev Notes:
- Started experimenting with adding a worker to our PKS environment.

### Step to PKS testing:
1. **Get access to the OPS MAN director**
    - username and pass: https://*OPS_MAN_URL*/api/v0/deployed/director/credentials/director_credentials
    - ca_cert: https://*OPS_MAN_URL*/api/v0/security/root_ca_certificate
    - IP (only accessible from pivotal network): https://*OPS_MAN_URL*/infrastructure/director/status
    - paste the cert to a file then run: `bosh -e https://DIRECTOR_IP/ login --ca-cert=PATH_TO_CERT` then enter the username and password.
    - run `bosh -e https://DIRECTOR_IP --ca-cert=PATH_TO_CERT pks`
    - run `bosh -e pks deployments` to verify the connection.

2. ** Create an external tagged worker on the same director to run PKS payloads**
    - Using the `external worker` option from the concourse-bosh-deployment repo
    - **stopped here** need to verify that there is a `Credhub` instance associated with the bosh director in order to store sensitive data like `tsa_host_key`
    - use the following vars file:
```yaml
deployment_name: concourse-worker
external_worker_network_name: default
worker_vm_type: medium
azs: default
instances: 1
```

    - use the `versions.yaml` file under `concourse-bosh-deployment` repo 
    - use the following ops file:
```yaml
- type: replace
  path: /instance_groups/name=worker/jobs/name=worker/properties
  value:
    tags: [pks]
```
3. ** Add the worker public key and tag to the prod deployment. **
4. ** Add a job to the main pipeline that runs `k8s-topgun` tests and tagged `pks` **
5. ** Add a tagged job to the main pipeline to upgrade the worker that runs with `bosh-prod-deploy` **

**Comment by taylorsilva** [comment]
We were able to start using our worker on the vsphere environment to run `k8s-topgun` and every single test started failing. Ran `kubectl describe pod` on a failing pod and found this error:

```
Warning  FailedMount         60s                    kubelet, a1be3f89-5b08-42a1-85d2-91e443e5fa91  Unable to mount volumes for pod "topgun-wr-83410291-worker-0_topgun-wr-83410291(85bb65d9-ae3f-11e9-89ec-005056b9048c)": timeout expired waiting for volumes to attach or mount for pod "topgun-wr-83410291"/"topgun-wr-83410291-worker-0". list of unmounted volumes=[concourse-work-dir]. list of unattached volumes=[concourse-work-dir pre-stop-hook concourse-keys topgun-wr-83410291-worker-token-npbqk]
  Warning  FailedAttachVolume  54s (x9 over 3m3s)     attachdetach-controller                        AttachVolume.Attach failed for volume "pvc-85ba84b9-ae3f-11e9-89ec-005056b9048c" : SCSI Controller Limit of 4 has been reached, cannot create another SCSI controller
```
The main error is this: `CSI Controller Limit of 4 has been reached, cannot create another SCSI controller`.

Found this article that adds a bit more context (but no solution) for this problem: https://orchestration.io/2018/06/13/storage-classes-in-pivotal-container-service-pks/

Thought that there was some orphaned `pvc`'s hanging around one of the pods
