### ISSUE TITLE
Cant see pipelines in concourse ui with my github credentials

### ISSUE THREAD

**Issue by kowshik9945** [concourse/ci#411]
I cant  see any pipelines in this link (https://ci.concourse-ci.org/) when i open with my github credentials,Do i need any different credentials to view the pipelines?

**Comment by matlinuxer2** [comment]
Could be the same issue to https://github.com/concourse/concourse/issues/8526

**Comment by taylorsilva** [comment]
Same issue. Closing this one as duplicate.
