### ISSUE TITLE
Address flakiness in k8s-smoke

### ISSUE THREAD

**Issue by cirocosta** [concourse/ci#44]
Hey,

[`k8s-smoke`][k8s-smoke], the job which deploys Concourse on Kubernetes (using
the [Helm chart][chart]) and then validates some basic functionality of it, has
been flaky for quite a while:

![Screen Shot 2019-07-04 at 12 07 48 PM](https://user-images.githubusercontent.com/3574444/60679062-5ad71f80-9e54-11e9-896b-710501435897.png)

We improved it a bit some time ago (https://github.com/concourse/concourse/pull/3947) 
but, still, we've been seeing some weirdness when trying to connect in the
`k8s-smoke` task:

- working:
  https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-smoke/builds/2098#L5d1e0b18:1:10
- not working:
  https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-smoke/builds/2097#L5d1bd110:12:16

A suggestion:

- look at what process is `exit`ing with a non 0 exit code

<br />

**Acceptance Criteria**

- [x] Have `k8s-smoke` running flawlessly for an entire day
  - seeing some 20 consecutive successful runs could be enough 

Thanks!

[k8s-smoke]: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-smoke
[chart]: https://github.com/helm/charts/blob/master/stable/concourse/README.md

**Comment by zoetian** [comment]
So PR's #48 and #49 were supposed to fix this but we're still seeing the error in ci.

Hijacked into the latest failed container and added `set -x` to the following scripts:

```
ci/tasks/scripts/k8s-deploy
ci/tasks/scripts/k8s-delete
ci/tasks/scripts/k8s-smoke
ci/tasks/scripts/smoke
ci/tasks/scripts/wait-workers
```
and then ran them all with this script:
```bash
#!/bin/bash

set -x

./ci/tasks/scripts/k8s-deploy
./ci/tasks/scripts/k8s-smoke
./ci/tasks/scripts/k8s-delete
```

**Comment by YoussB** [comment]
- after changes done by @zoetian and @pivotal-jamie-klassen, `k8s-smoke` has been running without errors since Friday, except for a case only [1 run](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-smoke/builds/2181) which seemed due to an irrelevant problem.

**closing**
