### ISSUE TITLE
Move concourse-charts pipeline to prod and add failure notification

### ISSUE THREAD

**Issue by YoussB** [concourse/ci#45]
### Background:
- We have a [pipeline](https://hush-house.pivotal.io/teams/main/pipelines/concourse-charts) running under [hush-house](https://github.com/concourse/hush-house) that updates the merged branch in `concourse/charts` repo to be a merging of the `helm/charts` master branch and branches that we specify in [this file](https://github.com/concourse/charts/blob/maintenance/refs.json) so then we can use this branch as an RC for the Concourse chart when we have unmerged PRs.
- This pipeline has been failing silently for some time now resulting in `k8s-topgun` failures.

### Request:
- This pipeline should be moved to our prod environment, so it can be easily monitored.
- Also, would be handy to add a slack notification for that whenever it fails (or maybe adding it to the concourse pipeline itself 🤔)

**Comment by taylorsilva** [comment]
We're going to move the pipline to prod. We are not going to include it in the main pipeline because it doesn't interact with any other part of the pipeline in a logical way.

**Comment by taylorsilva** [comment]
It's alive and green!
https://ci.concourse-ci.org/teams/main/pipelines/concourse-charts

ToDo's:
- [ ] Add pipeline to the reconfigure pipeline (a little hard because our pipeline is json...)
  - https://github.com/concourse/ci/blob/master/pipelines/reconfigure.yml
  - https://ci.concourse-ci.org/teams/main/pipelines/reconfigure-pipelines

**Comment by YoussB** [comment]
Hey, 
- I am not sure whether the pipeline resource works with json files or not, if it does, we can prepare the json in a separate job then input it to the reconfigure job 🤷‍♂ ?
- I like the YAML idea, I think we originally went with jsonnet since the resource pipelines are using jsonnet, I prefer YAML myself, it is more readable for me 😁 

Thanks 👍
