### ISSUE TITLE
include prod backups into the master pipeline

### ISSUE THREAD

**Issue by jamieklassen** [concourse/ci#6]
I think this would be a good means of dogfooding the Postgres release in a more realistic "production-like" setup. Might give a good example for curious community members, and hopefully gives us good empathy/experience to help bosh operators who use BBR.

**Comment by pivotal-jamie-klassen** [comment]
Let's do #8 first

**Comment by jamieklassen** [comment]
With #327 we're now leaving all the db-backing-up to GCP and doing none of it ourselves.
