### ISSUE TITLE
automatically assign PRs

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/ci#83]
In the interest of ensuring that PRs get the attention they deserve, let's think about proactively assigning them as soon as they appear. There may be some concerns about _who_ should be assigned what PR, or even whether an automated solution is overkill.

@nader-ziada could comment on how this has been done on other projects - i imagine via a github bot. If we're OK taking some bandwidth, it might be worth implementing something like this with a concourse pipeline, because dogfood.

**Comment by pivotal-jamie-klassen** [comment]
@clarafu also expressed interest in this topic

**Comment by pivotal-jamie-klassen** [comment]
very early research: https://github.com/imsky/pull-review

**Comment by pivotal-jamie-klassen** [comment]
I also poked around in https://github.com/octokit/rest.js and didn't see any methods for the "suggested reviewers" thing you see when you open a pull request.

**Comment by nader-ziada** [comment]
there is a thing that github has, but I have not used that before 
https://help.github.com/en/articles/about-code-owners

**Comment by nader-ziada** [comment]
The kubernetes projects I worked on before used Google's PROW ci, which has an assign feature that reads from an `owners` file in the repo
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/assign/assign.go
