### ISSUE TITLE
How can I tell which version of a resource type my resources are using, and when it changed?

### ISSUE THREAD

**Issue by jamieklassen** [concourse/ci#9]
Looks like we might be setting the status without a URI scheme, so they're being treated as relative links?

<img width="783" alt="Screen Shot 2019-06-05 at 2 48 56 PM" src="https://user-images.githubusercontent.com/22056320/58981879-42b2a880-87a1-11e9-8d82-c2813232f8d2.png">

**Comment by pivotal-jamie-klassen** [comment]
...and now they're working again. I find myself wondering how to check, within Concourse, whether a new version of a resource-type was discovered.
